shell = "fish"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dynamic_padding = true
decorations = "buttonless"
option_as_alt = "OnlyLeft"

[scrolling]
history = 10000
multiplier = 2

[font]

# ubuntu
# normal = {family = "UbuntuMono", style = "Regular"}
# offset = {x=0, y=-3}
# glyph_offset = {x=0, y=-2}

# macOs
normal = {family = "B612 Mono", style = "Regular"}
offset = {x=0, y=-3}
glyph_offset = {x=0, y=-2}

bold = {style = "Bold"}
italic = {style = "Italic"}

size = 15

[colors]

[bell]
animation = "EaseOut"
duration = 1
# color = "#220000"

[selection]
save_to_clipboard = true

[cursor]
# style = { shape="Beam", blinking="Always" }

[terminal]

[mouse]
hide_when_typing = true
bindings = [
  { mouse= "Right", mods="Control", action="Paste" },
]

[hints]

[keyboard]


